apiVersion: batch/v1
kind: CronJob
metadata:
  name: policyreport
spec:
  schedule: "0 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: policyreport
            image: mritunjay394/policyreport
          restartPolicy: Never
          serviceAccountName: clusterpolicyreport
