apiVersion: batch/v1
kind: CronJob
metadata:
  name: policyreport
spec:
  schedule: "0 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: policyreport
            image: ghcr.io/nirmata/kube-bench-adapter:v0.2.0
          restartPolicy: Never
          serviceAccountName: clusterpolicyreport
