name: Release container image

on:
  workflow_dispatch:
  push:
    tags:
      - 'v*'

env:
  KO_REGISTRY: ghcr.io/nirmata/kube-bench-adapter
  
jobs:
  publish:
    name: Publish
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      id-token: write
    outputs:
      operator-digest: ${{ steps.release-operator.outputs.digest }}

    steps:
      - uses: actions/setup-go@v4
        with:
          go-version: 1.21.5

      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Install KO
        uses: ko-build/setup-ko@v0.6

      - env:
          auth_token: ${{ secrets.GITHUB_TOKEN }}
          user: ${{ secrets.author }}
        run: |
          echo "${auth_token}" | ko login ghcr.io --username "${user}" --password-stdin 
          make ko-build
