name: Release container image

on:
  push:
    tags:
      - 'v*'

env:
  REGISTRY: ghcr.io
  REPOSITORY: enterprise-kyverno-operator
  IMAGE_NAME: nirmata/enterprise-kyverno-operator
  
jobs:
  publish:
    name: Publish
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      id-token: write
    outputs:
      operator-digest: ${{ steps.release-operator.outputs.digest }}

    steps:
      - uses: actions/setup-go@v4
        with:
          go-version: 1.21.5

      - uses: actions/checkout@v3

      - name: Install KO
        uses: ko-build/setup-ko@v0.6

      - run: make ko-build
