name: Go build and test

on:
  pull_request:
    branches:
      - 'main'

jobs:
  build:

    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-go@v4
        with:
          go-version: 1.21.5

      - uses: actions/checkout@v3

      - name: Build
        run: make
